site_name: Django PG Views Schema

nav:
  - Home: index.md
  - Installation: installation.md
  - Settings: settings.md
  - Get Started: get_started.md
  - Usage: usage.md
  - Features: features.md
  - Compatibility: compatibility.md


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deeppurple
      accent: deeppurple
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

  language: en
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - content.code.copy
plugins:
- search
# - mkdocstrings
